// Runtime access to LinkedIn-derived data. The YAML files under
// `content/linkedin/` are generated by `pnpm run sync:linkedin:csv` or
// `pnpm run sync:linkedin:api`; their shape is defined in `bin/linkedin/schema.ts`.
//
// The importers write the German source as `*.de.yml` (LinkedIn exports in
// the account's UI language — this account is German). English translations
// live in `*.en.yml` alongside. Use the `/translate-linkedin` skill to
// generate / refresh the EN siblings from DE.
//
// At runtime the EN file overrides the DE source per-field. When an EN field
// is missing, the DE value is surfaced — so partial translations degrade
// gracefully instead of going blank.

import type {Certification, Education, Language, Position, Profile, Project, Skill} from '../../bin/linkedin/schema';
import certificationsDe from '../../content/linkedin/certifications.de.yml';
import certificationsEnRaw from '../../content/linkedin/certifications.en.yml';
import educationDe from '../../content/linkedin/education.de.yml';
import educationEnRaw from '../../content/linkedin/education.en.yml';
import languagesDe from '../../content/linkedin/languages.de.yml';
import languagesEnRaw from '../../content/linkedin/languages.en.yml';
import positionsDe from '../../content/linkedin/positions.de.yml';
import positionsEnRaw from '../../content/linkedin/positions.en.yml';
import profileDe from '../../content/linkedin/profile.de.yml';
import profileEnRaw from '../../content/linkedin/profile.en.yml';
import projectsDe from '../../content/linkedin/projects.de.yml';
import projectsEnRaw from '../../content/linkedin/projects.en.yml';
import skillsDe from '../../content/linkedin/skills.de.yml';
import skillsEnRaw from '../../content/linkedin/skills.en.yml';

const positionsEn = (positionsEnRaw ?? []) as Array<Partial<Position>>;
export const educationEn = (educationEnRaw ?? []) as Array<Partial<Education>>;
const certificationsEn = (certificationsEnRaw ?? []) as Array<Partial<Certification>>;
const languagesEn = (languagesEnRaw ?? []) as Array<Partial<Language>>;
const skillsEn = (skillsEnRaw ?? []) as Array<Partial<Skill>>;
const projectsEn = (projectsEnRaw ?? []) as Array<Partial<Project>>;
const profileEn = (profileEnRaw ?? {}) as Partial<Profile>;

export const positions = positionsDe as Position[];
export const education = educationDe as Education[];
export const certifications = certificationsDe as Certification[];
export const languages = languagesDe as Language[];
export const skills = skillsDe as Skill[];
export const projects = projectsDe as Project[];
export const profile = profileDe as Profile;

function pickStr<T>(en: Partial<T> | undefined, de: T, key: keyof T): string {
  const v = en?.[key];
  return (typeof v === 'string' && v ? v : de[key]) as unknown as string;
}

// --- Derived views for site components ---------------------------------

function yearOf(d: string | null): string {
  return d ? d.slice(0, 4) : '';
}

function period(startedOn: string | null, finishedOn: string | null, todayLabel = 'Today'): string {
  const start = yearOf(startedOn);
  const end = finishedOn ? yearOf(finishedOn) : todayLabel;
  if (!start && !end) {
    return '';
  }
  if (start === end) {
    return start;
  }
  return start ? `${start} — ${end}` : end;
}

function parseYm(ym: string | null): {y: number; m: number} | null {
  if (!ym) {
    return null;
  }
  const [y, m] = ym.split('-').map(Number);
  if (!y) {
    return null;
  }
  return {y, m: m || 1};
}

function duration(
  startedOn: string | null,
  finishedOn: string | null,
  locale: 'en' | 'de',
): string {
  const s = parseYm(startedOn);
  if (!s) {
    return '';
  }
  const end = parseYm(finishedOn) ?? (() => {
    const d = new Date();
    return {y: d.getFullYear(), m: d.getMonth() + 1};
  })();
  let months = (end.y - s.y) * 12 + (end.m - s.m) + 1;
  if (months < 1) {
    months = 1;
  }
  const years = Math.floor(months / 12);
  const rem = months % 12;
  const labels = locale === 'de'
    ? {y1: 'Jahr', yN: 'Jahre', m1: 'Monat', mN: 'Monate'}
    : {y1: 'year', yN: 'years', m1: 'month', mN: 'months'};
  const parts: string[] = [];
  if (years > 0) {
    parts.push(`${years} ${years === 1 ? labels.y1 : labels.yN}`);
  }
  if (rem > 0) {
    parts.push(`${rem} ${rem === 1 ? labels.m1 : labels.mN}`);
  }
  return parts.join(' ');
}

export type ExpKind = 'position' | 'education';

export interface ExpEntry {
  kind: ExpKind;
  company: string;
  period: string;
  sortKey: string;
  endKey: string;
  roleEn: string;
  roleDe: string;
  locationEn: string;
  locationDe: string;
  durationEn: string;
  durationDe: string;
  employmentTypeEn: string;
  employmentTypeDe: string;
  stack: string[];
  descriptionEn: string;
  descriptionDe: string;
}

const POSITION_ENTRIES: ExpEntry[] = positions.map((p, i) => {
  const en = positionsEn[i];
  return {
    kind: 'position' as const,
    company: p.company,
    period: period(p.startedOn, p.finishedOn),
    sortKey: p.startedOn ?? '',
    endKey: p.finishedOn ?? '9999',
    roleDe: p.titleDe ?? p.title,
    roleEn: p.titleEn ?? pickStr(en, p, 'title'),
    locationDe: p.location,
    locationEn: pickStr(en, p, 'location'),
    durationDe: duration(p.startedOn, p.finishedOn, 'de'),
    durationEn: duration(p.startedOn, p.finishedOn, 'en'),
    employmentTypeDe: (p.employmentTypeDe ?? en?.employmentTypeDe ?? p.employmentType ?? en?.employmentType ?? ''),
    employmentTypeEn: (en?.employmentType ?? p.employmentType ?? ''),
    stack: (en?.stack ?? p.stack ?? []),
    descriptionDe: p.description,
    descriptionEn: pickStr(en, p, 'description'),
  };
});

const EDUCATION_ENTRIES: ExpEntry[] = education.map((e, i) => {
  const en = educationEn[i];
  return {
    kind: 'education' as const,
    company: e.school,
    period: period(e.startedOn, e.finishedOn),
    sortKey: e.startedOn ?? '',
    endKey: e.finishedOn ?? '9999',
    roleDe: e.degree,
    roleEn: pickStr(en, e, 'degree'),
    locationDe: e.location ?? '',
    locationEn: (en?.location ?? e.location ?? '') as string,
    durationDe: duration(e.startedOn, e.finishedOn, 'de'),
    durationEn: duration(e.startedOn, e.finishedOn, 'en'),
    employmentTypeDe: '',
    employmentTypeEn: '',
    stack: [],
    descriptionDe: e.activities ?? '',
    descriptionEn: pickStr(en, e, 'activities'),
  };
});

export const EXPERIENCE: ExpEntry[] = [...POSITION_ENTRIES, ...EDUCATION_ENTRIES]
  .sort((a, b) => (a.sortKey < b.sortKey ? 1 : a.sortKey > b.sortKey ? -1 : 0));

export interface CertEntry {
  year: string;
  nameDe: string;
  nameEn: string;
  issuerDe: string;
  issuerEn: string;
}

export const CERTIFICATES: CertEntry[] = certifications.map((c, i) => {
  const en = certificationsEn[i];
  return {
    year: yearOf(c.finishedOn ?? c.startedOn),
    nameDe: c.name,
    nameEn: pickStr(en, c, 'name'),
    issuerDe: c.authority,
    issuerEn: pickStr(en, c, 'authority'),
  };
});

export interface LanguageEntry {
  nameDe: string;
  nameEn: string;
  // ISO 3166-1 alpha-2 code of the flag to render — see `app/components/Flag.tsx`.
  flagCode: string;
  level: string;
  stars: number;
}

// Language name (DE or EN, case-insensitive) → flag code. Regional-indicator
// emoji don't render as flags on Windows, so we map to ISO codes and the
// `<Flag>` component renders inline SVGs instead.
const LANGUAGE_FLAG_CODES: Record<string, string> = {
  deutsch: 'de', german: 'de',
  spanisch: 'es', spanish: 'es',
  englisch: 'gb', english: 'gb',
  italienisch: 'it', italian: 'it',
  französisch: 'fr', french: 'fr',
};

function flagCodeFor(...names: Array<string | undefined>): string {
  for (const n of names) {
    const hit = n && LANGUAGE_FLAG_CODES[n.toLowerCase()];
    if (hit) {
      return hit;
    }
  }
  return '';
}

export const LANGUAGES: LanguageEntry[] = languages.map((l, i) => {
  const en = languagesEn[i];
  const nameDe = l.nameDe ?? l.name;
  const nameEn = l.nameEn ?? pickStr(en, l, 'name');
  return {
    nameDe,
    nameEn,
    flagCode: flagCodeFor(nameDe, nameEn, en?.nameEn),
    level: en?.level ?? l.level ?? l.proficiency,
    stars: en?.stars ?? l.stars,
  };
});

export const SKILLS_EN = skills.map((s, i) => skillsEn[i]?.name ?? s.name);
export const PROJECTS_DE = projects;
export const PROJECTS_EN = projects.map((p, i) => ({
  ...p,
  title: pickStr(projectsEn[i], p, 'title'),
  description: pickStr(projectsEn[i], p, 'description'),
}));
export const PROFILE_DE = profile;
export const PROFILE_EN: Profile = {
  firstName: profile.firstName,
  headline: pickStr(profileEn, profile, 'headline'),
  summary: pickStr(profileEn, profile, 'summary'),
  industry: pickStr(profileEn, profile, 'industry'),
  geoLocation: pickStr(profileEn, profile, 'geoLocation'),
};
