services:
  dev:
    build:
      context: .
      target: base
    working_dir: /opt/portfolio
    command: nix develop --command sh -c "pnpm install && pnpm run dev --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - .:/opt/portfolio
      - node_modules:/opt/portfolio/node_modules
    environment:
      NODE_ENV: development

volumes:
  node_modules:
